### ISSUE TITLE
glib/python3 circular dependency

### ISSUE THREAD

**Issue by techfury90** [sgidevnet/sgug-rse#103]
TL;DR: trying to build glib2 on my Octane fails because python 3.8wip is missing compileall2. Attempting to build 3.7.7 results in a dependency error on desktop-file-utils, which in of itself requires glib2 to build. Commented out the dependency to see what happens, waiting for build results...

**Comment by danielhams** [comment]
Thank you for the bug report, always useful to have the reminder for a release or upgrade cycle.

Indeed it seems this is a blocker to being able to smoothly build your way up through the WIP packages.

There may be (are certainly?) others lurking (looking at you, python tree).

Workaround as suggested by @techfury90 - comment out the desktop-file-utils dependency for the first build, get building and installed up to glib2, then restore the original spec file and rebuild, reinstall.

This will (hopefully) go away with either the next SP or the next point release of sgug-rse.

**Comment by danielhams** [comment]
0.0.6 is out and most of these python things should be resolved now (with 3.7.7 and proper macros + deps).
