### ISSUE TITLE
infocmp complains about a missing _nc_read_entry2

### ISSUE THREAD

**Issue by onre** [sgidevnet/sgug-rse#11]
```
[sgugshell esp@OCTODAD ~]$ infocmp
117013:infocmp: rld: Fatal Error: attempted access to unresolvable symbol in infocmp: _nc_read_entry2
[sgugshell esp@OCTODAD ~]$ ldd `which infocmp`
        libtic.so  =>    /usr/sgug/lib32/libtic.so
        libtinfo.so  =>  /usr/sgug/lib32/libtinfo.so
        libm.so  =>      /usr/lib32/libm.so
        libc.so.1  =>    /usr/lib32/libc.so.1
        libgcc_s.so.1  =>        /usr/sgug/lib32/libgcc_s.so.1

```
Everything installed from the binary distributions. I could try rebuilding to see if this goes away?

**Comment by danielhams** [comment]
Yeah quite possibly something broken in the binaries of ncurses. I found a rogue "libcurses.so" in `/usr/local/lib` that was being picked up due to the weird search path of binutils `ld` that might be the cause of this breakage.

**Comment by danielhams** [comment]
Workaround/fix for this in dc41a332a8e2c6a27583e9a3b5d51d0d35937bdf

(Forced import of the missing macro when it's not defined).

**Comment by danielhams** [comment]
Not mine to close .-) if you have a moment please retest + close if it OK for you.

**Comment by onre** [comment]
Working with 0.0.3.
