### ISSUE TITLE
SSHD irix init.d file

### ISSUE THREAD

**Issue by mgtremaine** [sgidevnet/sgug-rse#112]
openssh 8.1 in 0.5 has no sshd init.d file so I wrote one and offer it up for inclusion.

http://www.stellarcore.net/downloads/sgi/sshd.init

I named it sgug_sshd as SERVICE and copied the K02 and S98 files from neko_sshd. This would all have to be handled in POST INSTALL SCRIPT.

-Mike

**Comment by dillera** [comment]
Thanks for this mgtremaine, I'll work on incorporating it into our existing RPM which now has a properly working sshd server.

**Comment by mgtremaine** [comment]
I should add that I edited the sshd_config thusly  (which is why the do_keygen() exists in the init script). 

18,20c22,24
< #HostKey /etc/ssh/ssh_host_rsa_key
< #HostKey /etc/ssh/ssh_host_ecdsa_key
< #HostKey /etc/ssh/ssh_host_ed25519_key
---
> HostKey /usr/sgug/etc/ssh/ssh_host_rsa_key
> HostKey /usr/sgug/etc/ssh/ssh_host_ecdsa_key
> HostKey /usr/sgug/etc/ssh/ssh_host_ed25519_key

**Comment by ElCoyote27** [comment]
Just downloaded the script for the above URL and it seems to still look for neko_sshd in some places:

```
# grep neko sshd.init 
#User choice? This was to allow original sgi sshd and neko_sshd 
#Now changed to $SERVICE and neko_sshd but probably should just removed
if $IS_ON neko_sshd && $IS_ON $SERVICE && ! $IS_ON neko_sshd.force-start; then
    echo "Warning: both neko_sshd and $SERVICE are enabled; disabling neko_sshd." 1>&2
    echo "    contention and do 'chkconfig -f neko_sshd.force-start on'" 1>&2
    echo "    before re-enabling neko_sshd." 1>&2
    $IS_ON neko_sshd off

```

**Comment by dillera** [comment]
Thanks- but this wasn't used in the current fix. Another member packaged up the init scrips and put them all into the current openssh server RPMs that are in use now. I'll just close this out and point to the current fix! Thanks for brining it up to our attention.

**Comment by dillera** [comment]
Examine:
https://github.com/sgidevnet/sgug-rse/blob/wip-testing/packages/openssh/SPECS/openssh.spec

```
%changelog
* Sun Nov 07 2021 Vladimir Vukicevic <vladimir@pobox.com> - 8.1p1-12
- Add IRIX init file and chkconfig, fix sshd_config
```

vlad did a solid by picking this up and incorporating a nice working set of initd scripts. These are available when openssh is installed today via tdnf from the aws repo.

I posted this:
https://forums.sgi.sh/index.php?threads/setup-the-official-sgug-repo-upgrade-openssh.660/

which details how to eradicate the old nekko crap if you still have it intalled.

**Comment by ElCoyote27** [comment]
@dillera Thank you for doing this for the community!
