### ISSUE TITLE
python-rpm-macros-3-51 includes bashism that breaks builds

### ISSUE THREAD

**Issue by unxmaal** [sgidevnet/sgug-rse#114]
This package creates /usr/sgug/lib/rpm/macros.d/macros.pybytecompile .

This macro contains
`32 [[ "%1" =~ " -" ]] && echo "ERROR py_byte_compile: Path to interpreter should not contain any arguments" >&2 && exit 1 \`

mksh cannot interpret the =~ and will fail.

This prevents glib2 from building.

**Comment by onre** [comment]
Couldn't you do something like this: `echo "%1" | grep " -" && echo ...` - in this case it should have the same effect.

**Comment by danielhams** [comment]
FYI this was already fixed (by commenting out the check) in wip/wipnonautomated:

https://github.com/sgidevnet/sgug-rse/blob/wipnonautomated/packages/python-rpm-macros/SOURCES/macros.pybytecompile#L32

**Comment by unxmaal** [comment]
Yep, I just confirmed this. Closing.
