### ISSUE TITLE
libjpeg: retire old library, switch to libjpegturbo

### ISSUE THREAD

**Issue by danielhams** [sgidevnet/sgug-rse#116]
The original libjpeg in rse is actually libjpeg-9c.

It is currently used (depended on) by a number of packages - and was in place because libjpegturbo needs cmake to build (which we historically did not have back in the mists of time).

Someone needs to do the big painful job of switching over to libjpegturbo and then fixing all the packages currently linked against the older library to use the newer one.

Everything will need a version bump that is changing, and everything (going forward) should depend on libjpegturbo to avoid issues with "I installed a newer emacs and now it doesn't start" etc.

This is _not_ a simple change.

**Comment by unxmaal** [comment]
To clarify, when you say version bump, do you mean the least-significant number after the - ? Like foo-1.2.3-4 -> foo-1.2.3-5 ?

**Comment by danielhams** [comment]
Sorry, yeah indeed, I meant the `release` part of the package.

Just in general that's the thing for tracking (e.g. does user have the version with a bugfix in it).

**Comment by danielhams** [comment]
Changes merged, patching bundle will be available here when it finished uploading:

https://github.com/sgidevnet/sgug-rse/releases/tag/wipstarterpacks
