### ISSUE TITLE
libxml2 problems with "installed_prefix"

### ISSUE THREAD

**Issue by unxmaal** [sgidevnet/sgug-rse#118]
(Maybe this is linked to https://github.com/sgidevnet/sgug-rse/issues/72 ?)

After rebuilding python3.7 and deps  all weekend I see the same issue with libxml2 as I did earlier:

`make[4]: Entering directory '/usr/people/edodd/rpmbuild/BUILD/libxml2-2.9.9/py3/python'                                                         /usr/sgug/bin/sh ../libtool  --tag=CC   --mode=link mips-sgi-irix6.5-gcc  -O3 -g   -module -avoid-version ../libxml2.la   -L -lpython3.7m -lsock
et -lnsl -lintl -ldl  -lm  -Wl,-z,relro -Wl,--as-needed -Wl,-z,now -Wl,-rpath -Wl,/usr/sgug/lib32 -Wl,-rpath -Wl,/usr/lib32 -o libxml2mod.la -rp
ath /usr/sgug/lib32/python3.7/site-packages libxml.lo libxml2-py.lo types.lo
libtool:   error: require no space between '-L' and '-lpython3.7m'`

In ~/rpmbuild/BUILD/libxml2-2.9.9/py3/python/Makefile I see
`PYTHON_LIBS =  -L$(echo /usr/sgug/lib32 | sed s#/usr/sgug#$(installed_prefix /usr/sgug/bin/python3.7m-mips-config)#) -lpython3.7m -lsocket -lnsl -lintl -ldl  -lm` . 

It seems that during build, it's attempting to exec `installed_prefix /usr/sgug/bin/python3.7m-mips-config` in a subshell and failing.

I'm unable to determine where 'installed_prefix' should be. I don't see it in RSE, and I don't have it in /usr/sgug (or prior versions of). However, I do see it named as a function in  /usr/sgug/bin/python3.7m-mips-config .

Am I reading the Makefile wrong? Is sed not supposed to exec that? How is this supposed to work?

**Comment by danielhams** [comment]
Can you show what this returns:

`$ python3-config --ldflags -L/usr/sgug/lib32 -lsocket -lnsl -lintl -ldl -lm -lm`

At a guess this isn't a problem with libxml, but with python config not properly returning its ldflags or something.

**Comment by unxmaal** [comment]
$ python3-config --ldflags -L/usr/sgug/lib32 -lsocket -lnsl -lintl -ldl -lm -lm
Usage: exit_with_usage --prefix|--exec-prefix|--includes|--libs|--cflags|--ldflags|--extension-suffix|--help|--abiflags|--configdir

**Comment by danielhams** [comment]
Gah sorry, serves me right for rushing. Sorry let's try the _correct_ command .-)

`python3-config --ldflags`

Which should return

```
 -L/usr/sgug/lib32 -lpython3.7m -lsocket -lnsl -lintl -ldl  -lm
```

**Comment by unxmaal** [comment]
$ python3-config --ldflags
 -L$(echo /usr/sgug/lib32 | sed s#/usr/sgug#$(installed_prefix /usr/sgug/bin/python3.7m-mips-config)#) -lpython3.7m -lsocket -lnsl -lintl -ldl  -lm

**Comment by danielhams** [comment]
```
head `which python3.7m-mips-config`
```
Should look like this:
```
[sgugshell dan@leafy build0.0.6round2]$ head `which python3.7m-mips-config`
#!/usr/sgug/bin/sh

# Keep this script in sync with python-config.in

exit_with_usage ()
{
    echo "Usage: $0 --prefix|--exec-prefix|--includes|--libs|--cflags|--ldflags|--extension-suffix|--help|--abiflags|--configdir"
    exit $1
}
```

**Comment by unxmaal** [comment]
That matches.

(I'm also rebuilding python3, just in case.)

**Comment by unxmaal** [comment]
Rebuilding and reinstalling python3.7 fixed this:

```
$ python3-config --ldflags
 -L/usr/sgug/lib32 -lpython3.7m -lsocket -lnsl -lintl -ldl  -lm

```
