### ISSUE TITLE
0.0.6pre: shared-mime-info mime cache not built

### ISSUE THREAD

**Issue by unxmaal** [sgidevnet/sgug-rse#121]
`$ gdk-pixbuf-query-loaders |grep png
[sgugshell edodd@blue RPMS]$`

`$ sudo rpm -qa|grep gdk-pixbuf
gdk-pixbuf2-2.40.0-3.sgugprerelease0.0.6.mips
gdk-pixbuf2-modules-2.40.0-3.sgugprerelease0.0.6.mips
gdk-pixbuf2-xlib-2.40.0-3.sgugprerelease0.0.6.mips
gdk-pixbuf2-devel-2.40.0-3.sgugprerelease0.0.6.mips
gdk-pixbuf2-tests-2.40.0-3.sgugprerelease0.0.6.mips
gdk-pixbuf2-xlib-devel-2.40.0-3.sgugprerelease0.0.6.mips`

`$ rpm -qpl gdk-pixbuf2-*|grep loader
/usr/sgug/bin/gdk-pixbuf-query-loaders
/usr/sgug/lib32/gdk-pixbuf-2.0/2.10.0/loaders
/usr/sgug/lib32/gdk-pixbuf-2.0/2.10.0/loaders.cache
/usr/sgug/share/man/man1/gdk-pixbuf-query-loaders.1.gz
/usr/sgug/include/gdk-pixbuf-2.0/gdk-pixbuf/gdk-pixbuf-loader.h
/usr/sgug/lib32/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-ani.so
/usr/sgug/lib32/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-bmp.so
/usr/sgug/lib32/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-gif.so
/usr/sgug/lib32/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-icns.so
/usr/sgug/lib32/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-ico.so
/usr/sgug/lib32/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-jasper.so
/usr/sgug/lib32/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-jpeg.so
/usr/sgug/lib32/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-pnm.so
/usr/sgug/lib32/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-qtif.so
/usr/sgug/lib32/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-tga.so
/usr/sgug/lib32/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-tiff.so
/usr/sgug/lib32/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-xbm.so
/usr/sgug/lib32/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-xpm.so`

**Comment by danielhams** [comment]
Command to check this is:

```
cd /usr/people/edodd/rpmbuild/BUILD/gtk+-2.24.32/demos
/usr/sgug/bin/gdk-pixbuf-csource --raw --build-list apple_red  ./apple-red.png gnome_foot ./gnome-foot.png
```

**Comment by danielhams** [comment]
2nd confirm this fails on 0.0.6pre, and works fine on fc31.

Non-build test used:

```
[sgugshell dan@leafy sgug-rse.git]$ gdk-pixbuf-csource --raw --build-list apple_red /usr/sgug/share/gtk-2.0/demo/apple-red.png 
failed to load "/usr/sgug/share/gtk-2.0/demo/apple-red.png": Couldn’t recognize the image file format for file “/usr/sgug/share/gtk-2.0/demo/apple-red.png”
```

**Comment by danielhams** [comment]
Root cause of this is that the shared-mime-info package isn't correctly creating the mime type lookup cache that it should one first install.

It can be (for now) worked around be _reinstalling_ the `shared-mime-info` RPM file, which causes a trigger to fire regenerating the lookup cache.

I'll have a think about how we can work around this for 0.0.6 (real).

**Comment by danielhams** [comment]
0.0.6 has a bit of a hacky "generate the cache on install" but it seems to do the trick (for this).
