### ISSUE TITLE
Supplying both -pthread and -lpthread causes a segfault

### ISSUE THREAD

**Issue by onre** [sgidevnet/sgug-rse#13]
```
#include <iostream>
#include <cstdlib>
#include <pthread.h>

using namespace std;

#define NUM_THREADS 5

void *PrintHello(void *threadid) {
   long tid;
   tid = (long)threadid;
   cout << "Hello World! Thread ID, " << tid << endl;
   pthread_exit(NULL);
}

int main () {
   pthread_t threads[NUM_THREADS];
   int rc;
   int i;

   for( i = 0; i < NUM_THREADS; i++ ) {
      cout << "main() : creating thread, " << i << endl;
      rc = pthread_create(&threads[i], NULL, PrintHello, (void *)i);

      if (rc) {
         cout << "Error:unable to create thread," << rc << endl;
         exit(-1);
      }
   }
   pthread_exit(NULL);
}
``` 

Crashes with `g++ threads.cpp -pthread -lpthread`, works with `g++ threads.cpp -pthread`. For now, "don't do it then!" is a good enough workaround, but this probably shouldn't happen. For some reason I suspect this may have more to do with binutils than compiler.

**Comment by danielhams** [comment]
I think 1d26a77 will fix this - but I've made other changes too that might be per-requisites for the full fix.

Suggest waiting for 0.0.4 full rebuild before checking.

**Comment by danielhams** [comment]
0.0.4 is out and I think you're updated - when you have time to check this please do :-)

**Comment by onre** [comment]
Works now, closing.
