### ISSUE TITLE
Desktop Apps: Work out standard way to add SGUG to IMD toolbox

### ISSUE THREAD

**Issue by danielhams** [sgidevnet/sgug-rse#141]
Now we start to have some GUI applications that are useful, it would be nice that these appear inside the Indigo Magic toolbox with nice icons.

There was a post in the SGUG forums about setting the right flags on executables that would be the place to look about what needs to be done to the application themselves - but perhaps we can abuse the existing desktop-file-utils or whatever it's called as the place to hook into "new GUI application added, do some magic to add it to the toolbox".

This is a new feature - so I suggest we trial it in a few steps:

(1) How to set the right flags on pidgin to be able to create the icon / shortcut style thing
(2) How to hook into new applications becoming available in a centralised package
(3) How to them use the hook so that some toolbox area for SGUG has things added and removed.

**Comment by dillera** [comment]
Path forward.
