### ISSUE TITLE
Move sgugshell to actual package

### ISSUE THREAD

**Issue by danielhams** [sgidevnet/sgug-rse#147]
We recommend people currently use sgugshell in the readme - and that currently means you need git to checkout the repository.

A better solution is that sgugshell is a standalone package included in the minimal tarball - and git _is not_.

1) Create a sgugshell package that installs the shell script in `/usr/sgug/bin` without any shell extension
2) Change the "sgugshell.sh" script in the git repo to just run `/usr/sgug/bin/sgugshell`
3) Change the sgug-rpm-tools package - remove "git-all" from the minimum package list, include sgugshell
4) Update the readme.md so a clone isn't needed - just running of `/usr/sgug/bin/sgugshell`

**Comment by danielhams** [comment]
Extra info:

RE: sgugshell / sgug-rpm-tools - I preferred these two being separate so we can say "put the sgugshell in the minimal install ball but not sgug-rpm-tools". You can put them in the same package if that's your decision - but that means putting "sgug-rpm-tools" in the minimum tarball then.

(I'd have to check what the deps of sgug-rpm-tools is to see if it pulls in anything unexpected, basically)

**Comment by dillera** [comment]
Sure, makes sense. Then I can make two rpms no problem.

**Comment by danielhams** [comment]
sgug-rpm-tools is already an RPM, FYI. sgugshell itself doesn't even really need a standalone project.

In wipnonautomated, just create
`packages/sgugshell/SPECS`
and
`packages/sgugshell/SOURCES`

Then place the sgugshell script in `SOURCES` (please rename to remove the `.sh` extension) and place your worked on `sgugshell.spec` in the `SPECS`.

Inside the `.spec` you refer to the script as a `Source0: sgugshell` - and it should pull it from `~/rpmbuild/SOURCES`.

That's how I'd take a stab at it, anywho .-)

Please consider the above hints, not "it must be done this way" . Cheers.

**Comment by dillera** [comment]
Yep, suggestions and tips welcome. I have a good pattern for adding scipts like this. Will have something today to look at.

**Comment by danielhams** [comment]
Will be in 0.0.7dev (and 0.0.7 proper, too).
