### ISSUE TITLE
openssh: client warnings + server not installable

### ISSUE THREAD

**Issue by danielhams** [sgidevnet/sgug-rse#15]
Running the ssh client gives warnings about `unsupported option "gssapi"`. This is probably a config file issue.

The openssh-server is currently not installable - and in fact I've done no work to ensure it's setup correctly with a user or that the "right thing" is done vis-a-vis `/etc/init.d/` scripts.

Caution: Having the existing RPM script install / modify things _outside_ of the `/usr/sgug` prefix is something that needs to be discussed further - because it means

(a) It's a pain to build the self hoster if it includes files outside of the prefix
(b) Really we want any RPMs that do this kind of thing to be installed _after_ the self-hoster is in place - so that the correct `post`/`pre` triggers are executed for user creation / permissions etc.

**Comment by danielhams** [comment]
See also #24 about some standard replacement for managing groups/users etc so that other packages can work out of the box.

**Comment by dillera** [comment]
Gssapi is just a quick comment on the option to fix that. The issue is that while the host keys are there, the sshd will not read them and won't exactly say why not (even when run in debug mode).

You start sshd in debug mode and keep it from forking like this:

/usr/sgug/sbin/sshd -ddd


I'm working on deeper debugging, moving sshd to port 2222 allows you to keep neko sshd working for now on 22.

This must be related to something in openssl, as I see issues with git reading rsa keys for cloning repos.

**Comment by danielhams** [comment]
Client warning resolved in a28ba4e23e3a8a89bb86aa03a1f5bfa374199076 by removing the redhat config install. Still work to do on the server portion.

**Comment by dillera** [comment]
Some issues building, but your RPMs work great. The server works. Will help tweak w/ the init script from NS and a post-install script to install users and create host keys.

**Comment by danielhams** [comment]
A contributor has suggested an init script in #112 - I haven't checked that or indeed looked into what other options there are.

There is also a note in the repo openssh package directory with some historical suggestions that people have made:

https://github.com/sgidevnet/sgug-rse/blob/wipnonautomated/packages/openssh/init.dnote.txt

**Comment by dillera** [comment]
Yes, I will work on getting that conrib into the RPM and ensure it installs and works with IRIX 6.5.x.

**Comment by dillera** [comment]
This is resolved! Thanks @vvuk ! Done and tested.
