### ISSUE TITLE
Where to put "general" directories that packages require?

### ISSUE THREAD

**Issue by danielhams** [sgidevnet/sgug-rse#152]
Example:

Our gnupg2 requires a runtime directory under which it will create directories per user to put it's unix domain socket.

So for root, it creates a directory like `/usr/sgug/var/run/user/0/`.

I prefer not to have gnupg2 itself own the parent directory `/usr/sgug/var/run/user` - so we need find a good place to transfer the ownership and get it owned by that.

One possibility might be RPM itself, or one of the "base" sgug packages.

**Comment by dillera** [comment]
won't fix
