### ISSUE TITLE
alienblaster (a game?) errors out for missing deps

### ISSUE THREAD

**Issue by chulofiasco** [sgidevnet/sgug-rse#177]
alienblaster doesn’t start up.

[sgugshell root@IRIS /]# alienblaster
3929:alien-blaster.bin: rld: Fatal Error: cannot successfully map...

photo attached
![0F91D44E-F1BE-443D-9FC8-9FDEB4BC51E8](https://user-images.githubusercontent.com/87949542/126912323-dd732d30-6a99-412f-9ea9-17a813d320ba.jpeg)

**Comment by Jenna64bit** [comment]
Interesting. With the sudo call, you aren't passing environment variables such as the library path right, there are flags I cannot remember offhand to do that but it isn't looking in /usr/sgug/lib32 at all.

For the first error, though, it is looking for the sgug library. SDL_Mixer 1.2 and SDL 1.2 are available, so this is either a compilation or installation requirements fail. >.<

**Comment by dillera** [comment]
install SDL from repo.
