### ISSUE TITLE
warning: user dan does not exist - using root

### ISSUE THREAD

**Issue by oweidner** [sgidevnet/sgug-rse#187]
When I follow the instructions in Readme.md to rebuild an RPM from source, I get this warning:

```
[oweidner@indy SPECS]% rpm -ivh ../SRPMS/mpg123-1.25.10-2.sgug.src.rpm
Updating / installing...
   1:mpg123-1.25.10-2.sgug            warning: user dan does not exist - using root
################################# [100%]
warning: user dan does not exist - using root
warning: user dan does not exist - using root
```

**Comment by unxmaal** [comment]
It's not a problem, it just means that when the source package was created, the files were owned by the user 'dan' on that machine. When RPM installs a package it tries to set the same owner, group, and permissions, and falls back to root when the owner or group are not found.

**Comment by oweidner** [comment]
Ok, that makes sense. Closing this issue.
