### ISSUE TITLE
strlcpy missing from libc

### ISSUE THREAD

**Issue by LaurentChardon** [sgidevnet/sgug-rse#191]
I didn't see this documented in the READMEs. Is there a minimum version of IRIX that is required? Or am I supposed to use an alternative libc? I get an unresolvable symbol error with sgug-rse 007 beta

**IRIX version 6.5.19m**
```
[sgugshell laurent@octane ~]$ /sbin/uname -aR
IRIX64 octane 6.5 6.5.19m 01100304 IP30
```

**Several binaries are not working due to missing strlcpy**
```
sgugshell laurent@octane ~]$ sudo ls
 1973:sudo: rld: Fatal Error: attempted access to unresolvable symbol in sudo: strlcpy
[sgugshell laurent@octane ~]$ sh  
 1971:sh: rld: Fatal Error: attempted access to unresolvable symbol in sh: strlcpy
[sgugshell laurent@octane ~]$ zless
 1977:/usr/sgug/bin/sh: rld: Fatal Error: attempted access to unresolvable symbol in /usr/sgug/bin/sh: strlcpy
```

**Using the system libc**
```
[sgugshell laurent@octane ~]$ ldd /usr/sgug/bin/sh
        libc.so.1  =>    /usr/lib32/libc.so.1
```

Do I need to upgrade my version of IRIX or will compiling from source fix this?

**Comment by dillera** [comment]
At the moment the only fully tested and supported version of IRIX are 6.5.30 and 6.5.22. 

Are you able to upgrade your Octane?

**Comment by LaurentChardon** [comment]
Thanks for your reply! I found tar archives of the overlay disks for 6.5.22, I'll upgrade.

**Comment by dillera** [comment]
No problem- jump on the forums or discord if you need more help: http://sgi.sh
