### ISSUE TITLE
boost: iostreams library missing

### ISSUE THREAD

**Issue by onre** [sgidevnet/sgug-rse#31]
Can't find iostreams library anywhere. Headers are in place, though.

**Comment by onre** [comment]
Looking at the spec file it seems like this is disabled on purpose. Any idea how painful it'd be to get working? Could take a stab at it.

**Comment by danielhams** [comment]
Honestly I can't remember if it just doesn't compile, I couldn't test it, or I didn't care .-)

By all means have a pop if you think you can.

**Comment by danielhams** [comment]
Will be activated / built with 0.0.5.

**Comment by danielhams** [comment]
Resolved in 0.0.5beta.
