### ISSUE TITLE
Do a pass double checking I've not left redhat/fedora assets or naming

### ISSUE THREAD

**Issue by danielhams** [sgidevnet/sgug-rse#7]
To be polite it would be good to do a pass double checking that there isn't any Redhat or Fedora assets or naming left in place.

Off the top of my head, there's a least the perl-Fedora-* package that probably need renaming (and what depends on it).

**Comment by danielhams** [comment]
As a minimum, I'd like to see that someone has a full install of all packages and performs a find for all common image types, then filters that for anything containing "fedora" or "redhat" -> and we see if they need removing.

**Comment by Conan-Kudo** [comment]
It's generally okay to leave modules alone that are APIs (`perl-Fedora-*`, `python-fedora`, etc.). Packages like `redhat-rpm-config` are supposed to be replaced with your own variant, and you should set your own `--with-vendor=` label in the rpm package.

**Comment by danielhams** [comment]
Hi Conan-Kudo,

Thanks for your input - indeed I think we are setting the vendor and arch correctly:

```
[sgugshell dan@leafy mips]$ rpm -qi rpm-4.15.0-13.sgugbeta.mips.rpm 
Name        : rpm
Version     : 4.15.0
Release     : 13.sgugbeta
Architecture: mips
Install Date: (not installed)
Group       : Unspecified
Size        : 3742829
License     : GPLv2+
Signature   : (none)
Source RPM  : rpm-4.15.0-13.sgugbeta.src.rpm
Build Date  : Fri Jun 12 20:21:31 2020
Build Host  : leafy.modular-audio.co.uk
URL         : http://www.rpm.org/
Summary     : The RPM package management system
Description :
The RPM Package Manager (RPM) is a powerful command line driven
package management system capable of installing, uninstalling,
verifying, querying, and updating software packages. Each software
package consists of an archive of files along with information about
the package like its version, a description, etc.
[sgugshell dan@leafy mips]$ rpm -E "%{_vendor}"
sgug
```

So at the very least since the get go, our output SRPM and RPM files won't get confused with any "official" redhat/fedora pieces and it's clear "they ain't fedora".

Thanks for the nudge about the renaming of `redhat-rpm-config` - indeed, I recently saw that quite a few of the macros in there weren't being picked up because they were originally under the `%{_prefix}/lib/rpm/redhat` -> they've since been moved - but the renaming of the package itself is still TODO.

We've still got a ways to go of course (wip branch is the ongoing pieces) - for the moment we're still installing/uninstalling directly with rpm commands.

**Comment by danielhams** [comment]
Moving away from "redhat-rpm-config" to sgug specific packages with similar intent in 101ecb3238ada198448e23a502ea8a97dc67d4e0.

This will include https://github.com/sgidevnet/sgug-rse/tree/wipnonautomated/packages/sgugrse-repos and https://github.com/sgidevnet/sgug-rse/tree/wipnonautomated/packages/sgug-release.

Lots more to do, but this isn't forgotten.
