### ISSUE TITLE
python3-config from python3-3.8.1-2wip.sgugbeta.mips does not function properly

### ISSUE THREAD

**Issue by unxmaal** [sgidevnet/sgug-rse#72]
Currently this script emits `$ python3-config --ldflags
 -L$(echo /usr/sgug/lib32 | sed s#/usr/sgug#$(installed_prefix /usr/sgug/bin/python3-config)#)  -lsocket -lnsl -lintl -ldl  -lm -lm`

When changed to use bash, it runs properly:

`$ python3-config --ldflags
 -L/usr/sgug/lib32  -lsocket -lnsl -lintl -ldl  -lm -lm`

**Comment by danielhams** [comment]
I did look at this a little bit - the "fix" to rewrite the various hardcoded shells in the Python source isn't too bad - but it doesn't "solve" the problem with building python bindings of libxml2 (for example).

The deeper issue with building python bindings comes from some bug or configuration problem I've yet to track down in rpmbuild and the auto-python-bytecompile.

I will keep at it. For now, you can tweak the path as you suggest (knowing that it's _not the full fix_).

**Comment by danielhams** [comment]
Lots more aggressive re-writing of hardcoded paths in this change in wip: https://github.com/sgidevnet/sgug-rse/commit/b86019d02fdcc88c10b5fd6bedfdd1283243d463

Please give that version a poke and if OK for you we can close.

**Comment by danielhams** [comment]
Seems to be OK with 3.7.7 python3 in WIP, please re-test.
