### ISSUE TITLE
Debug info missing (changed title as GDB is in 0.0.3)

### ISSUE THREAD

**Issue by danielhams** [sgidevnet/sgug-rse#8]
We're missing the GDB package.

Also, regular Fedora automagically extracts package debug info so that GDB can use it. The auto-extraction may never work (the elftools under rpm were hacked up just enough to get rpm working).

**Comment by danielhams** [comment]
gdb will be included in 0.0.3alpha.

It's going to take longer to work out what is needed for auto-extracted debug info unfortunately.

**Comment by danielhams** [comment]
Update: So as part of fixing issues with `elfdeps` auto-extraction of dependency provides and requires - buildid extraction was "semi-working" - but caused all kinds of corner case breakage when attempting to rebuild packages. gcc doesn't build at all - whinging about some build id link _already being made_.

For 0.0.4 there won't be detection of `buildid` by rpmbuild and auto-debug info extraction will have to come later.

**Comment by danielhams** [comment]
Note that for 0.0.4 I've made a temporary change to /usr/sgug/lib/rpm/brp-strip to ensure that libraries are stripped (this is normally done as part of the debug info extraction).

That will need rolling back once proper debug info extraction is in place.

**Comment by dillera** [comment]
Daniel where are you.
