### ISSUE TITLE
Python3 script "pathfix.py" is used in gtk2's spec

### ISSUE THREAD

**Issue by unxmaal** [sgidevnet/sgug-rse#84]
This script, found in the Python source at Python-3.8.1/Tools/scripts/pathfix.py , is referenced in the gtk2.spec:

`# Use python3 shebang instead of ambiguous python
pathfix.py -pn -i %{__python3} $RPM_BUILD_ROOT%{_bindir}/gtk-builder-convert`

There's various things we could do here, including

- add the Tools to our python package
- add this one script into the gtk2 package as a patch
- something better

**Comment by danielhams** [comment]
"New" python3 (actually a rollback) 3.7.7 in WIP, give that a poke, it seems to be installed now.

**Comment by danielhams** [comment]
In 0.0.6 - and out now.
