### ISSUE TITLE
GCC/binutils - support static linking of libgcc

### ISSUE THREAD

**Issue by danielhams** [sgidevnet/sgug-rse#9]
For unknown reasons as of 0.0.1alpha gcc + binutils revert to dynamically linking in libgcc_s.so all the time, which is a pain.

Using the `-static-libgcc` doesn't do the trick - and in fact check most autoconf projects and you'll notice that it doesn't detect gcc as being able to static link at all during discovery.

**Comment by danielhams** [comment]
First investigation is that the `-static-libgcc` isn't being passed through libtool to the linker behind. When it is passed manually, the shared library or executable does indeed link in stuff from the static libraries.

**Comment by danielhams** [comment]
Possible line of investigation around copysignl symbol resolution problems too:

https://gcc.gnu.org/ml/gcc-patches/2008-10/msg00292.html

We might be missing some macros in the math bits and it ends up needing libm etc.

**Comment by dillera** [comment]
Closing for now as won't do.
